# UnstuckPlugin Configuration

# Time in seconds between uses of /unstuck command
cooldown-seconds: 30

# Radius from current position to search for a safe spot
search-radius: 5

# Maximum number of attempts to find a safe location
max-attempts: 50

# Y-coordinate range for safe locations
# These are adjusted based on world min/max Y if necessary
min-y: 32
max-y: 120

# Enable debug logging (only use for troubleshooting)
debug: false
