name: Stuck
version: '6.1'
main: com.orang.stuck.Stuck
api-version: '1.21'
description: 'A plugin to help players get unstuck from glitched terrain'
author: adasjusk

commands:
  stuck:
    description: Teleports you to a nearby safe location
    usage: /stuck
    aliases: [escape]
    permission: stuck.use
permissions:
  stuck.use:
    description: Allows use of the /stuck command
    default: true
